"""Content for the implementation workbook and runbook. Planning only."""
from pathlib import Path
import csv, json, math
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'output/multimodal-implementation'
OUT.mkdir(parents=True, exist_ok=True)
ROLES = {'MD':'Managing Director','CD':'Commercial Director','TD':'Technical Director','PAE':'Process Applications Engineer','HP':'Head of Product and AI','AI':'Applied AI Engineer','KE':'Knowledge Engineer','SEC':'Parent security lead','EXP':'Contracted expert or independent reviewer','OPS':'Contracted implementation specialist'}
CAPACITY = {'MD':240,'CD':240,'TD':480,'PAE':720,'HP':480,'AI':960,'KE':960,'EXP':1000,'OPS':300,'SEC':160}
TASKS=[]
def task(id,phase,title,owner,day,duration,deps,hours,section,inputs,steps,output,acceptance,reviewer='TD',review_hours=2):
    TASKS.append(dict(id=id,phase=phase,title=title,owner=owner,not_before=day,duration=duration,predecessors=deps.split() if deps else [],hours=hours,section=section,inputs=inputs,steps=steps,output=output,acceptance=acceptance,reviewer=reviewer,review_hours=review_hours,status='Not started',percent=0))

# Durations are elapsed working days. Effort is separate person-hours.
task('A01','Mobilize','Define three pilot workflows','HP',1,2,'',12,1,'CTO plan and refining scope','Specify evidence review, diagnostic brief and calculation support; list allowed users and excluded operating actions.','charter.md and workflow list','Technical Director accepts scope and prohibited actions.')
task('A02','Mobilize','Assign named delivery and review owners','MD',1,3,'',10,1,'Seven-role organization and contracted support','Protect the role hours; appoint separate content authors and reviewers; reserve parent security capacity.','staffing.csv and reviewer roster','Named owner and independent reviewer for each workstream.','HP')
task('A03','Mobilize','Measure current engineering workflow','CD',3,4,'A01',24,18,'Representative internal engineering questions','Time at least ten manually prepared briefs; record complexity, corrections and acceptance rubric before tool use.','baseline_effort.csv','Baseline includes review time and task mix; no fabricated ROI.','HP',4)
task('A04','Mobilize','Normalize all existing source leads','KE',2,3,'',18,3,'32 general and 19 Norm source-register rows','Retain original IDs; distinguish models, software, data, articles and catalogs; assign processing recipe and priority.','source_register.csv','All 51 prior rows mapped; catalogs remain acquisition leads.','MD',3)
task('A05','Mobilize','Approve rights and data-use contract fields','MD',3,5,'A04',20,3,'Candidate source terms and intended internal use','Record acquisition, OCR, retrieval, SFT, evaluation, processor, retention and derived-weight permissions separately; resolve publisher and former-client rights.','rights_ledger.jsonl and grant templates','Every admitted use has evidence; unknown permissions remain held.','SEC',8)
task('A06','Mobilize','Approve hosting and access architecture','SEC',3,5,'A01 A02',24,2,'Data classes and expected GPU capacity','Choose region and processors; separate quarantine, retrieval, training and evaluator identities; allow model-download egress only.','environment_design.md','Evaluator answer store cannot be read by trainer or production retriever.','HP',4)
task('A07','Mobilize','Create annotation and acceptance rubrics','TD',4,5,'A01 A02',24,8,'Launch questions and expert availability','Define factual, visual, numeric and missing-evidence rubrics; fix critical-error definitions and review rules.','rubrics_v1.json','Two reviewers agree on trial labels and adjudication method.','EXP',8)
task('G0','Gate','G0 authorize baseline work','MD',10,1,'A03 A05 A06 A07',4,1,'Charter, rights route, staffing and environment design','Record scope, spend limit, named owners and unresolved source holds.','gate_G0.json','Only cleared sources and approved environment may enter baseline work.','HP',2)
task('B01','Environment','Provision isolated storage and identities','OPS',11,3,'G0',20,2,'Approved architecture','Create raw, extracted, curated, retrieval, models, runs and evaluator stores; configure encryption, access groups and audit events.','storage_inventory.json and access tests','Cross-role deny tests pass, including image URLs and caches.','SEC',6)
task('B02','Environment','Create GPU environment and dependency lock','AI',11,3,'G0',18,12,'Approved Linux GPU image and candidate model cards','Install compatible PyTorch, Transformers, TRL, PEFT, Datasets, Pillow and Accelerate in a disposable environment; record CUDA and driver.','requirements.lock and container digest','Imports and GPU/BF16 checks succeed; exact versions or Git commits captured.','OPS',4)
task('B03','Environment','Pin model and retrieval repository revisions','HP',11,2,'G0',8,12,'M01 M02 M03 M05 M06 model cards','Select Qwen3.5-4B as candidate and Qwen3-8B as control; resolve full commit SHA and license for each; defer alternate until needed.','model_manifest.json','No floating main or unreviewed remote code in the release manifest.','SEC',3)
task('B04','Environment','Download and verify model artifacts','AI',14,2,'B01 B02 B03',10,12,'Approved repository IDs and SHAs','Download original safetensors, configs, tokenizer and processor files; compute per-file SHA256; preserve license and card.','models snapshots and hashes.json','Shard index resolves; all weights and processor files present; no document corpus mixed into model directory.','OPS',3)
task('B05','Environment','Run text and image inference smoke tests','AI',16,2,'B04',12,12,'Pinned model and synthetic fixtures','Load locally; generate one text response and one image response; test ordered two-image input and an empty image list.','compatibility_report.json','No missing architecture or image-token errors; save peak memory and latency.','HP',4)
task('B06','Environment','Inspect adapter targets and loss masking','AI',18,3,'B05',20,14,'Loaded model named modules and collator','Select explicit language-layer projections; exclude visual encoder and projector; inspect one mixed batch and all label masks.','target_modules.txt and mask_report.json','Only intended LoRA weights are trainable; prompt/image/padding tokens have no supervised loss.','OPS',6)
task('B07','Environment','Prove train save reload compatibility','AI',21,3,'B06',18,14,'Two approved or synthetic examples','Run ten optimizer steps on a fixture; save adapter and processor; reload with exact base; compare deterministic logits within agreed tolerance.','smoke adapter and reload_report.json','Finite loss, gradient updates, successful reload and reproducible outputs. Fixture is excluded from production data.','HP',4)
task('C01','Intake','Build intake manifest and quarantine handler','AI',14,3,'B01 A05',18,4,'Authorized source files and grants','Compute asset SHA256, sniff MIME, scan in isolation, block macros, assign source and family IDs, record custody and parent attachments.','intake_manifest.jsonl','Repeated intake is idempotent; rejected or held assets cannot advance.','SEC',4)
task('C02','Intake','Acquire first cleared document sample','KE',14,3,'B01 A05',16,3,'P01 P02 and authorized original expert sample','Obtain exact official editions or authorized files; retain URL/date/edition and item-level notices; admit only cleared uses.','initial raw batch and grant records','Full documents present; no preview or search snippet presented as a complete work.','MD',3)
task('C03','Intake','Implement digital PDF and HTML extraction','AI',17,3,'C01 C02',20,5,'Cleared digital PDF or HTML sample','Use Docling or equivalent pinned parser; retain page/heading coordinates, table cells and captions; save JSON and Markdown views.','documents.jsonl and figures','Reading order and page coverage checked against originals.','KE',6)
task('C04','Intake','Implement scan OCR and image extraction','OPS',17,4,'C01 C02',24,5,'Scanned pages and engineering figure sample','Render lossless page images near 300 dpi; orient/deskew a derivative; OCR; preserve original coordinates and transforms.','page PNGs, regions.jsonl and OCR flags','All critical values, units, subscripts and arrows independently checked; unreadable fields stay unknown.','PAE',8)
task('C05','Intake','Implement Word and slide extraction','KE',18,3,'C01',16,6,'Authorized DOCX and PPTX work papers','Extract paragraphs, tables, notes and image anchors; record revisions and slide IDs; do not accept tracked changes silently.','normalized work-paper records','Comments, notes and revisions are explicitly included or excluded by rule.','PAE',4)
task('C06','Intake','Implement engineering image annotation','PAE',21,5,'C04 A07',28,7,'Approved PFD, P&ID, sketch and trend examples','Create overview plus bounded crops; label legibility, tags, units, values, arrows and connections; attach caption and scope.','visual_labels.jsonl','No inferred hidden connectivity; every label points to a visible region.','EXP',12)
task('C07','Intake','Implement email thread normalization','KE',21,4,'C01 A05',20,6,'Authorized EML or MBOX export and attachments','Preserve Message-ID, replies, timezones and attachment relationships; deduplicate quotes; redact identities; separate question-time facts from later outcomes.','threads.jsonl and attachment manifest','Chronology retained; replies and third-party attachments receive separate permission review.','SEC',5)
task('C08','Intake','Implement tabular operating-data conversion','PAE',21,4,'C01',24,7,'Authorized CSV XLSX or historian export','Export values with units, timestamps, timezone and quality flags; preserve original formulas; distinguish gauge/absolute pressure and missing readings.','measurements.parquet and data_dictionary.json','Sampled values reconcile to original; no silent interpolation or unit conversion.','EXP',6)
task('C09','Intake','Implement interview transcription route','KE',24,4,'C01 A05',20,6,'Consented WAV MP3 MP4 interview sample','Create timestamped transcript and speaker labels; verify technical terms with expert; select only instructional frames; link all derivatives to source time.','segments.jsonl, transcript and selected PNGs','Expert approves technical transcript; separate grants for recording, slides and reuse.','EXP',10)
task('C10','Intake','Normalize text tables equations and units','PAE',25,4,'C03 C04 C05 C08',22,8,'Extracted documents and measurements','Normalize Unicode and whitespace conservatively; keep raw text; represent tables with row/column headers and equations with variable definitions.','canonical evidence records','Decimal signs, inequalities, exponents, units and footnotes reconcile; failed regions quarantined.','EXP',8)
task('C11','Intake','Add deduplication and case-family grouping','AI',25,3,'C03 C04 C07',16,8,'Asset hashes, text and attachment links','Detect exact duplicates and near duplicates; group republished articles, revisions, email replies, crops and synthetic variants into one family.','family_manifest.jsonl','Known duplicate pairs stay together; similarity hits reviewed rather than deleted blindly.','KE',6)
task('C12','Intake','Create batch audit and retry controls','OPS',28,2,'C10 C11',10,4,'Extraction results and failures','Record parser/model revision, state, failure reason and output hashes; retry only changed or failed assets; keep held rows out of downstream exports.','batch_audit.jsonl and rejection queue','Reprocessing unchanged input produces no duplicate evidence or training records.','AI',3)
task('D01','Curation','Author first original expert cases','KE',17,6,'C02 A07',32,9,'Cleared expert interviews or authored notes','Capture symptom, regime, question-time evidence, alternatives, discriminating checks, outcome and limitations; get author sign-off.','case packets batch 1','No client identifiers or restricted source text without explicit clearance.','EXP',24)
task('D02','Curation','Freeze initial family splits','TD',24,2,'D01 C11',12,9,'Family manifest and case inventory','Assign families to train/dev/test before variants; allocate evaluator-only answer access; tag all child assets with inherited split.','split_manifest_v1.jsonl','No family crosses splits; test-family answers absent from trainer and retrieval.','EXP',8)
task('D03','Curation','Build first 400 reviewed SFT examples','KE',26,4,'D02 C10 C06',40,10,'Training families and structured evidence','Write 300 text and 100 visual prompt/completion records; attach evidence; check answer visibility and reviewer provenance.','train_v0.jsonl and linked PNGs','400 accepted records; every image resolves and every answer has review evidence.','EXP',50)
task('D04','Curation','Build baseline development questions','TD',26,4,'D02',18,16,'Development families and rubric','Create tasks from 20 dev families; separate prompts, references and scoring keys; ensure visual/text paired comparisons.','dev_v0 and gold answers','No development example enters SFT; task mix documented.','EXP',16)
task('E01','Retrieval','Build evidence chunks and citation mapping','AI',24,3,'C03 C06 C10',18,11,'Canonical cleared evidence','Split by section at proposed 400-800 tokenizer tokens; retain table/caption integrity, parent references, page regions, family and access metadata.','chunks.jsonl','Every chunk resolves to an authorized original and has deterministic ID.','KE',5)
task('E02','Retrieval','Load lexical and vector retrieval index','AI',27,3,'E01 B04',18,11,'Approved chunks and pinned embedding model','Embed approved text; store vectors with model revision/dimension; create lexical index; apply access and split filters before candidates.','retrieval index v0','Known positives retrievable and unauthorized or test-answer chunks excluded.','SEC',5)
task('E03','Retrieval','Create first validated calculation tools','PAE',18,8,'A07 B01',40,11,'Selected property and unit operations','Implement typed unit conversion and one bounded balance/property tool; validate independent values and out-of-range errors; record tool version.','tool schemas and reference fixtures','Golden values within preset tolerance; wrong units and unsupported fluids rejected.','EXP',16)
task('G1','Gate','G1 accept working baseline','HP',30,1,'B07 D03 D04 E02',4,1,'First 400 examples, compatibility report and evidence index','Review baseline readiness and checked tool availability; approve paired vision benchmark.','gate_G1.json','Model loads/trains/reloads; corpus and test segregation work; E03 completed.','TD',4)
task('E04','Retrieval','Benchmark retrieval and tune chunk policy','AI',31,4,'G1 E03',24,11,'Engineer-labeled evidence queries','Measure recall at 20 candidates; test 400/600/800 token chunks and overlaps on dev data; use same settings across model comparisons.','retrieval_eval.csv and frozen policy','Proposed 90% recall@20 target assessed with denominators; missing evidence investigated.','PAE',6)
task('E05','Retrieval','Add reranker and evidence packaging','AI',35,3,'E04',16,11,'Permitted retrieval candidates and M06','Rerank only authorized candidates; select top evidence within token budget; retain image region links and cited IDs.','context_pack schema and baseline','Citations resolve; forbidden candidates cannot enter reranker or output.','SEC',4)
task('E06','Retrieval','Test revocation and index versioning','OPS',36,3,'E05',16,11,'Grant expiry fixture and indexed copies','Revoke one source; remove text, vectors, images and cached contexts; verify old release is not served to unauthorized users.','revocation_report.json','Zero retrieval hits or cache leaks from revoked grant under tested identities.','SEC',5)
task('F01','Baseline','Compare text OCR and native vision','TD',31,7,'G1 E03',24,16,'Paired development questions and untuned models','Run Qwen3-8B text, Qwen3.5 text/OCR and Qwen3.5 image paths with identical evidence and tools; blind and counterbalance review.','baseline_predictions.jsonl and paired scores','Record quality, critical errors, timing, GPU memory and cost; isolate image contribution.','EXP',30)
task('F02','Baseline','Decide model and visual scope','HP',38,2,'F01 E05 E06',10,16,'Paired results and compatibility evidence','Retain native vision only with supported quality or review-time gain; record selected model revision, accepted visual types and fallback.','architecture_decision.md','Five-point acceptance or 15% review-time improvement is supported; inconclusive results narrow scope.','TD',4)
task('G2','Gate','G2 authorize adaptation tranche','MD',40,1,'F02 E06',4,1,'Architecture decision and refreshed forecast','Approve remaining spend and exact selected scope; defer unsupported image tasks.','gate_G2.json','Rights, staffing and evidence justify continuation.','HP',3)
task('D05','Curation','Acquire and admit production source batches','KE',31,25,'G1',80,3,'Prioritized cleared source list','Process launch documents and expert packets in weekly batches; follow the source routing sheet; keep excluded datasets out.','weekly intake batches','Coverage grows without converting catalog leads or uncleared previews into content.','MD',12)
task('D06','Curation','Expand and reconcile 300 case families','KE',41,20,'G2 D05',90,9,'Accepted evidence and expert-authored incidents','Assemble 180 train, 60 dev and 60 test families; track equipment and visual coverage; keep scenario variants within parent family.','family_manifest_v2.jsonl','300 independent families supported by provenance; at least 90 train and 30 each dev/test have usable visual evidence.','EXP',60)
task('D07','Curation','Author remaining 1600 examples','KE',61,10,'D06',90,10,'Approved training families','Add 1200 text and 400 image/text records to initial batch; follow diagnostic, clarification, tool, grounding and escalation quotas.','train_v1.jsonl','Final 1500 text and 500 visual examples; every answer has evidence and independent review.','EXP',160)
task('D08','Curation','Build full development and locked suites','TD',61,10,'D06',40,16,'60 dev families and 60 locked test families','Create 120 locked case tasks and 180 challenge prompts; keep gold evaluator-only; tag task subtype and tolerances.','dev_v1 and sealed test v1','Test suite families disjoint; challenge prompts distinguished from independent incidents.','EXP',80)
task('D09','Curation','Audit data rights lineage and contamination','KE',71,3,'D07 D08',22,9,'Final manifests and all derivative IDs','Check grants, review states, exact/near duplicates and answer phrases against retrieval and prompts; trace teacher generation sources.','dataset_audit.json and release manifest','No unauthorized use or cross-split family; rejected records listed with reason.','SEC',6)
task('D10','Curation','Package portable SFT datasets','AI',74,2,'D09',14,10,'Accepted JSONL and local images','Validate schema, materialize image paths, create Hugging Face runtime rows; strip governance metadata from model inputs; hash export.','train/dev release and dataset_card.md','Images and placeholders match; no remote URL fetch; frozen test data not mounted on training host.','KE',4)
task('F03','Training','Implement processor and token preflight','AI',41,5,'G2 B07',26,13,'Selected model processor and pilot examples','Use shipped chat template; check prefix masks and image tokens; count full processed length; reject records beyond 8192-token proposal.','preflight_report.json','No silent truncation; supervised labels only on approved answer tokens.','OPS',8)
task('F04','Training','Set training configuration and tracking','HP',46,3,'F03',14,14,'Train compatibility and memory profile','Start BF16 LoRA rank16, alpha32, one epoch, LR5e-5; freeze visual encoder; set batch1 accumulation16 seed17 and spend limit.','run_config.json and run tracker','Config includes base/processor/data hashes, explicit module list and observed effective batch.','AI',4)
task('F05','Training','Run pilot adapter learning curve','AI',49,6,'F04 D03',30,14,'First approved 400 examples and dev set','Train on 100/200/400 record subsets grouped by family; compare held-out dev quality and runtime; inspect failures and memorized passages.','learning_curve.csv and pilot adapters','Stop on NaN, leakage, loss-mask errors or critical regression; do not use locked tests.','TD',8)
task('F06','Training','Tune bounded development configurations','AI',55,12,'F05',52,14,'Pilot findings and expanding approved data','Compare ranks16/32 and LR5e-5/1e-4; at most eight configs per finalist; retain text-only and untuned controls.','experiment register and candidate recipe','Selection based on dev quality, effort and critical errors; not training loss alone.','HP',8)
task('F07','Training','Train final adapter and seed repeats','AI',76,3,'D10 F06',20,14,'Frozen 2000-example release and selected recipe','Train selected mixed model and text-adapter control; repeat finalist seeds; preserve checkpoints and budget/quality logs.','candidate adapter and seed results','No held-out reuse; exact inputs and settings reconstruct each run.','TD',6)
task('F08','Training','Export reload and compare tuned candidate','AI',79,1,'F07',8,15,'Final adapter and pinned base','Save adapter safetensors/config and processor; reload in fresh environment; compare to untuned same-input model on dev.','candidate_manifest.json and adapter report','Tuning gain meets proposal or release keeps untuned baseline; memory and latency recorded.','HP',3)
task('G3','Gate','G3 freeze release candidate','HP',80,1,'F08 D08 D09',4,1,'Reproducible model, corpus, tools and development report','Freeze all release versions and commit candidate to independent evaluation.','gate_G3.json','2000 approved examples and 300 family manifest reconcile; no open critical development defect.','TD',3)
task('H01','Application','Build internal evidence review interface','OPS',41,10,'G2 E05',50,17,'Context pack and brief schema','Show source passage/image crop beside editable extracted facts and brief; capture acceptance, corrections and escalation reason.','review UI build','Reviewers can verify every cited source and correct misread values before accepting.','PAE',8)
task('H02','Application','Build inference and tool service','AI',51,10,'H01 E03',40,15,'Model baseline, tool schemas and auth policy','Add bounded inference endpoint; validate structured outputs and tool calls; reject arbitrary shell/URL actions; enforce request limits.','internal service build','Permissions enforced server-side; unknown tools/units rejected; no plant-control writes.','SEC',10)
task('H03','Application','Integrate serving adapter and processor','AI',81,4,'G3 H02',22,15,'Frozen candidate and serving environment','Use supported Transformers serving first; test vLLM only if exact adapter/vision path works; compare quantized and original outputs before selection.','serving_manifest.json','Selected backend reproduces accepted answers and image preprocessing; no silent fallback to base model.','OPS',6)
task('H04','Application','Build monitoring and controlled feedback queue','OPS',61,8,'H02',36,17,'Review logs and retention policy','Record evidence IDs, release IDs, errors, latency and review outcomes; quarantine feedback; redact sensitive logs; implement access-aware deletion.','monitoring and feedback workflow','No online retraining; correction becomes data only after rights and expert review.','SEC',6)
task('I01','Evaluation','Run locked independent technical evaluation','TD',85,5,'H03 D08',28,16,'Sealed 120 tasks and candidate service','Independent reviewers score blind; apply prespecified denominators, tolerances and critical-error veto; log failures by family and modality.','locked_eval_v1.jsonl','At least85% accepted diagnostic tasks,95% grounded claims,98% critical legible values and numeric checks; no critical failures.','EXP',60)
task('I02','Evaluation','Run challenge and security tests','SEC',85,5,'H03 D08',28,17,'180 challenge prompts and access matrix','Test image/text injections, fake citations, wrong units, cross-project access, expired grants, resource exhaustion and unsafe tool requests.','security_report.json','Zero unauthorized disclosure/actions in tested cases; no unresolved high-severity finding.','OPS',10)
task('I03','Evaluation','Measure workload and reviewer efficiency','HP',86,5,'H03 A03',20,16,'Fixed workload, baseline times and reviewers','Test five concurrent users, measured token/image budget and up to three tools; counterbalance human comparison tasks; compute per-accepted-brief cost.','performance_and_effort.csv','Report p95, rejection rate and median review effort; investigate deviations from60-second proposal.','CD',8)
task('I04','Evaluation','Remediate and prepare fresh evaluation cases','AI',90,6,'I01 I02 I03',30,16,'Failure records and independent reviewer capacity','Fix affected component; refresh holdout for material fixes exposed by locked suite; rerun targeted and critical regression tests.','remediation ledger and fresh holdout','No reuse of exposed test cases as sole proof of corrected generalization. If insufficient cases, defer gate.','EXP',30)
task('I05','Evaluation','Test backup restore and rollback','OPS',90,4,'H03 H04',20,17,'Versioned candidate and backup policy','Restore sources/review records within approved recovery window; deploy previous version; revoke access and verify audit trail.','restore_rollback_report.json','Four-business-hour restore and24-hour review-record loss objectives demonstrated or revised before approval.','SEC',5)
task('I06','Evaluation','Sign technical security and release records','HP',97,3,'I04 I05',10,17,'Acceptance reports and resolved issue ledger','Obtain separate Technical Director and security acceptance; package user guidance, monitoring and recovery procedures.','release_manifest.json','Single product release owner has both prerequisite acceptances.','TD',4)
task('G4','Gate','G4 authorize supervised internal pilot','MD',100,1,'I06',4,1,'Signed release and operations readiness','Authorize only named internal users and supported tasks for four weeks.','gate_G4.json','No critical open defect; funding and reviewer coverage available.','HP',2)
task('J01','Pilot','Onboard ten internal pilot users','CD',101,3,'G4',18,18,'Approved release and user list','Train users to inspect evidence, correct units, reject unsupported answers and escalate issues; verify access groups.','onboarding records','Each user completes a supervised sample; no external access.','TD',4)
task('J02','Pilot','Run supervised briefs and weekly reviews','PAE',104,14,'J01',90,18,'Internal engineering requests','Target100 reviewed briefs; record acceptance, corrections, time and sources; second-review weekly sample; stop affected capability on critical defect.','pilot_briefs.jsonl and weekly metrics','Every brief reviewed; limitations and incidents recorded, including refusals.','EXP',80)
task('J03','Pilot','Measure pilot value and operating cost','HP',115,4,'J01',20,18,'Reviewed brief log and cloud/reviewer costs','Compare accepted-brief effort with baseline task mix; report quality, availability, cost and uncertainty; forecast continuing service cost.','pilot_report.md','No savings claim without observed accepted quality and recorded labor.','CD',8)
task('J04','Pilot','Prepare continuation and next backlog','MD',119,1,'J02 J03',6,18,'Pilot findings and risk register','Recommend continue, narrow or stop; propose next data gaps and budget; customer use remains a separate rights and product decision.','continuation_memo.md','Board receives evidence, residual limits and named owners.','TD',3)
task('G5','Gate','G5 decide continuation','MD',120,1,'J04',4,1,'Pilot report and continuation memo','Record continue/narrow/stop decision and release scope.','gate_G5.json','No implied commercial launch or automatic model expansion.','HP',2)

# AWS foundation work is the first execution milestone. It uses public model
# weights and synthetic fixtures while business/source onboarding runs alongside.
updates={
 'B01':dict(title='Launch AWS GPU workspace and private S3 stores',not_before=1,predecessors=[],inputs='Existing authorized AWS sandbox, region, network and spend envelope',steps='Follow AWS 2: choose g6e.2xlarge and a compatible PyTorch GPU DLAMI; attach encrypted 300 GiB gp3 EBS; use Session Manager and an instance role; create private versioned S3 model, data, run and evaluator stores; record resource IDs. Use only public model weights and synthetic fixtures until G0.',output='aws_environment.json, GPU host and S3 inventory',acceptance='Session Manager works; nvidia-smi detects one L40S; S3 role tests pass; evaluator bucket is denied to trainer. Account/quota/network access confirmed before day 1.'),
 'B02':dict(title='Prepare PyTorch environment on AWS GPU host',not_before=1,duration=2,hours=12,predecessors=['B01'],inputs='AWS GPU host and DLAMI PyTorch environment',steps='Follow AWS 3: activate the AMI PyTorch environment, create an isolated overlay, keep the AMI CUDA/PyTorch stack, install model libraries, run pip check and CUDA/BF16 checks. Save AMI, driver, Python and package inventory.',output='candidate-requirements.txt and environment report'),
 'B03':dict(title='Pin the Hugging Face foundation model revision',not_before=1,duration=1,hours=4,predecessors=[],inputs='Qwen/Qwen3.5-4B model card and Apache-2.0 license',steps='Choose the post-trained image/text checkpoint as the starting foundation. Resolve and save its full repository SHA and license evidence. Other candidates remain comparison options; pin embeddings separately when building retrieval.',output='foundation_revision.json',acceptance='Exact model revision and license recorded; no floating model revision in subsequent runs.'),
 'B04':dict(title='Download Qwen3.5 weights into AWS and archive in S3',not_before=1,duration=1,hours=6,predecessors=['B01','B02','B03'],inputs='AWS environment, pinned foundation revision and aws_start scripts',steps='Run foundation_download.py on EC2 using the reviewed revision. Download safetensors, tokenizer, processor and config files to /srv/broadbridge/models; verify shards; hash all artifacts; copy the immutable revision folder to the private S3 model bucket. See AWS 3.',output='Local model snapshot, SHA256 manifest and private S3 copy',acceptance='All weight shards and model/processor files exist; S3 copy count and sampled hashes reconcile; no proprietary source data sent to Hugging Face.'),
 'B05':dict(title='Run the foundation model in AWS on text and images',not_before=1,predecessors=['B04'],steps='Run foundation_smoke.py with the local model snapshot and synthetic chart. Record text and image answers, memory and timing. Extend check to ordered two-image input and empty image list. Archive baseline outputs in S3. See AWS 4.',output='baseline_smoke.json and compatibility_report.json'),
 'B06':dict(not_before=1),
 'B07':dict(not_before=1)
}
for t in TASKS:
    t.update(updates.get(t['id'],{}))
TASKS[:]=[t for t in TASKS if t['id'].startswith('B')]+[t for t in TASKS if not t['id'].startswith('B')]
# Source work remains behind the original business/data acceptance gate.
for t in TASKS:
    if t['id'] in ['C01','C02'] and 'G0' not in t['predecessors']:t['predecessors'].append('G0')
    if t['id']=='E02':
        t['steps']='Download and hash pinned Qwen3-Embedding-0.6B and Qwen3-Reranker-0.6B snapshots to AWS. '+t['steps']

by={t['id']:t for t in TASKS}
def dates(t,trail=()):
    if 'start_day' in t:return
    assert t['id'] not in trail, 'Dependency cycle'
    for p in t['predecessors']:dates(by[p],trail+(t['id'],))
    t['start_day']=max([t['not_before']]+[by[p]['finish_day']+1 for p in t['predecessors']])
    t['finish_day']=t['start_day']+t['duration']-1
for t in TASKS:dates(t)
# Conservative daily leveling of assigned task and review effort. These are peak
# availability assumptions, not additional headcount or an automatic retainer.
DAILY={r:8 for r in ROLES}; DAILY['EXP']=24
usage=defaultdict(lambda:defaultdict(float))
ordered=sorted(TASKS,key=lambda t:(t['start_day'],t['finish_day'],t['id']))
for t in ordered:
    t['target_not_before']=t['not_before']
    t['duration']=max(t['duration'],math.ceil(t['hours']/DAILY[t['owner']]),math.ceil(t['review_hours']/DAILY[t['reviewer']]))
    start=max([t['not_before']]+[by[p]['finish_day']+1 for p in t['predecessors']])
    daily=defaultdict(float)
    daily[t['owner']]+=t['hours']/t['duration'];daily[t['reviewer']]+=t['review_hours']/t['duration']
    while any(usage[r][d]+h>DAILY[r]+1e-8 for r,h in daily.items() for d in range(start,start+t['duration'])):start+=1
    t['start_day']=start;t['finish_day']=start+t['duration']-1
    t['not_before']=start
    for r,h in daily.items():
        for d in range(start,t['finish_day']+1):usage[r][d]+=h
assert max(t['finish_day'] for t in TASKS)<=180
assert len({t['id'] for t in TASKS})==len(TASKS)

RECIPES=[
 ['R01','Digital PDF or licensed article','PDF; authorized HTML capture','Preserve binary and rights; extract native text, tables, headings, page regions and figures; compare reading order; strip navigation, not source qualifications.','JSONL evidence; Markdown review view; PNG figures; cell-structured tables','Retrieval after clearance; SFT only from reviewed case records','Pages complete; units and tables match; article boundaries exact','C01 C03 C10'],
 ['R02','Scanned PDF or handwritten paper','Original PDF TIFF JPEG PNG','Render about300dpi; save orientation transform; OCR to region records; retain original plus derivative; verify handwriting and critical symbols manually.','PNG pages/crops; OCR JSON with boxes and quality flags','Retrieval and reviewed image/text examples','Unreadable values remain unknown; no invented characters','C04 C06 C10'],
 ['R03','Work paper or seminar slides','DOCX PPTX and linked assets','Extract paragraphs, tables, slide notes and images; retain revisions, authorship and slide anchors; export fixed-layout preview for review.','JSONL evidence; PNG figure/slide; review Markdown','Reviewed retrieval and training when specifically permitted','Notes/comments policy explicit; formulas and diagram captions retained','C05 C10'],
 ['R04','Private email or public Q and A thread','EML MBOX; MSG only via approved export','Preserve message IDs, order, timestamps and attachments; remove repeated quotes with pointers; redact personal data; label question-time evidence versus subsequent resolution.','Thread JSONL; redacted text; attachment assets','Case reconstruction only after sender/client/content rights','No later answer leaked into diagnostic prompt; attachments separately admitted','C07 D01'],
 ['R05','Diagram or equipment photograph','Original CAD/PDF and PNG/TIFF/JPEG export','Keep native original; select overview and bounded crops; annotate tags, values, arrows, regions and legibility; attach revision and equipment context.','RGB PNG/JPEG plus region/edge JSONL','Visual evidence retrieval and paired SFT examples','No hidden connectivity inferred; CAD properties not assumed from pixels','C06'],
 ['R06','Historian trend or tabular measurements','CSV XLSX Parquet approved historian export','Capture units, timezone, gauge/absolute basis, quality and missing values; retain raw observations; validate transformations; plot from checked numeric data.','Parquet numeric table; JSON dictionary; optional PNG plot','Numeric tools plus reviewed visual examples','Original numeric values preferred over digitized chart estimates','C08'],
 ['R07','Interview audio or instructional video','WAV MP3 M4A MP4 original','Record consent; transcribe with timestamps and speaker IDs; expert-correct terminology; sample meaningful frames; pair frame/time and transcript.','Transcript JSONL; selected PNGs; original recording','Text/visual curriculum; no raw audio training in release1','Instructor clears transcript and selected frames; no voice cloning','C09'],
 ['R08','Hugging Face instruction dataset','Pinned JSON JSONL CSV Parquet or Arrow snapshot','Review dataset and underlying source grants; inspect schema and examples; map to canonical fields; group source families; verify every domain answer; run dedup.','Approved canonical JSONL and image assets','Only admitted task-relevant records; held sources stay excluded','Dataset-card label alone is insufficient source lineage','D05 D09 D10'],
 ['R09','Foundation model or embedding model','Safetensors shards and JSON/tokenizer/processor files','Resolve full commit; preserve license/card; download pinned files; hash; load in isolated compatible environment; test image/text and adapter paths.','Pinned model directory plus manifest','Model runtime; never ingest weights as document content','Exact model, tokenizer and processor revisions work together','B02 B03 B04 B05 B06 B07'],
 ['R10','Engineering software or property data','Pinned source/package; licensed property tables','Audit license/backends; limit fluids/equations/ranges; validate independent cases; expose typed checked calculation tool.','Tool JSON schema; versioned runtime; golden fixtures','Tool execution and checked synthetic examples','Model does not invent property values or trust unvalidated simulation','E03'],
 ['R11','Catalog preview bibliography or unavailable paper','URL metadata and authorized preview','Record title, authors, edition and rights contact; seek full authoritative asset; keep catalog text out of technical case labels.','Acquisition lead only','No technical training until full asset and rights admitted','No preview presented as full book or paper','A04 A05 C02'],
 ['R12','Held benchmark or later practice source','Source metadata only at this stage','Keep excluded/NC/unknown-lineage material out; evaluate future domain fit and permissions separately; benchmarks never enter training.','Hold record or evaluator-only dataset after clearance','Deferred or evaluation only','No upstream competence inferred from refining evaluation','A04 A05 D09']
]

def source_routes():
    rows=[]
    for f in ['Broadbridge_Training_Source_Register.csv','Norm_Lieberman_Source_Register.csv']:
        for x in csv.DictReader((ROOT/'output/training-sources'/f).open(encoding='utf-8-sig')):
            id=x['source_id']; name=x.get('name',x.get('title')); url=x.get('source_url',x.get('url',''))
            route='R01'; decision='Acquire and review item rights before use'; taskids='A05 C02 C03 D05'
            if id.startswith('M'):
                route='R09';decision='Candidate; pin and validate before loading';taskids='B02 B03 B04 B05'
                if id in ['M07','M08','M09']:route='R12';decision='Hold; rights or lineage unresolved; no pilot use';taskids='A05'
                if id=='M04':decision='Optional drafting teacher; approved inputs only; independent answer review'
            if id in ['P07','P08']:route='R10';decision='Implement as checked tool, not raw document training';taskids='E03'
            if id=='P06':route='R06';decision='Optional dated context tool; exclude from diagnostic answer labels';taskids='C08'
            if id in ['P09','P10','P11','K04']:route='R12';decision='Held permission review or later practice; not first refining pilot';taskids='A05'
            if id.startswith('D'):route='R12';decision='Hold or later evaluation per original register; not launch SFT';taskids='A05 D09'
            if id=='K01':route='R07 / R03';decision='Original contracted cases preferred; candidate appointment only';taskids='A05 C09 D01'
            if id in ['K02','K03']:route='R11 then R01';decision='Obtain exact licensed full work; separate expert appointment';taskids='A05 C02 D05'
            if id=='K05':route='R04 / R06';decision='Site-only retrieval by default; no shared SFT without grant';taskids='A05 C07 C08'
            if id=='K06':route='R01 / R05';decision='Licensed retrieval only unless separate training grant';taskids='A05 C03 C06'
            if id=='N01':route='R04 / R01';decision='Separate each post, correspondent and embedded asset';taskids='A05 C03 C07'
            if id in ['N09','N10','N11','N13','N14','N15','N16','N17','N19']:route='R11 then R01';decision='Acquire full exact paper/book/article; previews and catalogs are leads only';taskids='A05 C02 D05'
            if id=='N12':route='R11 then R07';decision='License recordings, frames and quizzes separately; evaluator quizzes isolated';taskids='A05 C09 D08'
            rows.append([id,name,route,decision,taskids,url,'Not acquired or processed in this implementation task'])
    assert len(rows)==51
    return rows

REFS=[
 ['HF01','Qwen3.5 candidate model','https://huggingface.co/Qwen/Qwen3.5-4B','Model artifacts and publisher runtime guidance'],
 ['HF02','Qwen3.5 Transformers implementation','https://huggingface.co/docs/transformers/main/en/model_doc/qwen3_5','Model class and processor compatibility'],
 ['HF03','Hub downloads','https://huggingface.co/docs/huggingface_hub/guides/download','Pinned snapshot acquisition'],
 ['HF04','TRL dataset formats','https://huggingface.co/docs/trl/en/dataset_formats','Prompt/completion and image inputs'],
 ['HF05','TRL SFT trainer','https://huggingface.co/docs/trl/en/sft_trainer','Trainer and loss/truncation behavior'],
 ['HF06','PEFT LoRA','https://huggingface.co/docs/peft/main/package_reference/lora','Adapter configuration'],
 ['HF07','PEFT checkpoint format','https://huggingface.co/docs/peft/main/en/developer_guides/checkpoint','Adapter artifacts and base dependency'],
 ['HF08','Datasets image loading','https://huggingface.co/docs/datasets/image_load','Image dataset loading'],
 ['HF09','Embedding model','https://huggingface.co/Qwen/Qwen3-Embedding-0.6B','Candidate embedding model'],
 ['HF10','Reranker model','https://huggingface.co/Qwen/Qwen3-Reranker-0.6B','Candidate reranker'],
 ['DOC01','Docling supported formats','https://docling-project.github.io/docling/usage/supported_formats/','Candidate extraction tool; prove on engineering samples'],
 ['LOCAL01','Existing source registers','Broadbridge_Training_Source_Register.csv and Norm_Lieberman_Source_Register.csv','Source status inherited from23 September2026 review; not new permission evidence']
]

if __name__=='__main__':
    from aws_start import AWS_ROWS,AWS_REFS
    payload=dict(tasks=TASKS,roles=ROLES,capacity=CAPACITY,daily_capacity=DAILY,recipes=RECIPES,sources=source_routes(),refs=REFS+AWS_REFS,aws_rows=AWS_ROWS)
    (OUT/'implementation_data.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False),encoding='utf-8')
    with (OUT/'Broadbridge_Implementation_Tasks.csv').open('w',newline='',encoding='utf-8-sig') as f:
        fields=list(TASKS[0]);w=csv.DictWriter(f,fields);w.writeheader()
        for t in TASKS:w.writerow({**t,'predecessors':'; '.join(t['predecessors'])})
    print(json.dumps({'tasks':len(TASKS),'gates':[(t['id'],t['finish_day']) for t in TASKS if t['phase']=='Gate'],'finish_day':max(t['finish_day'] for t in TASKS),'sources':len(source_routes())}))
